name: risuai

services:
  risuai:
    container_name: risuai
    image: ghcr.io/kwaroran/risuai:latest
    restart: always
    ports:
      - 6001:6001
    volumes:
      - risuai-save:/app/save

volumes:
  risuai-save:
