import {
  FolderIcon,
  StarIcon,
  HeartIcon,
  SparklesIcon,
  FlameIcon,
  SunIcon,
  MoonIcon,
  CloudIcon,
  ZapIcon,
  CrownIcon,
  GemIcon,
  GiftIcon,
  CoffeeIcon,
  Gamepad2Icon,
  MusicIcon,
  CameraIcon,
  ImageIcon,
  FileIcon,
  UserIcon,
  UsersIcon,
  PawPrintIcon,
  LeafIcon,
  SproutIcon,
  CarIcon,
  PlaneIcon,
  HouseIcon,
  BookOpenIcon,
  BookmarkIcon,
  PenIcon,
  ScrollTextIcon,
  SwordIcon,
  ShieldIcon,
  WandSparklesIcon,
  SkullIcon,
  GhostIcon,
  CatIcon,
  DogIcon,
  RabbitIcon,
  BirdIcon,
  FishIcon,
  BugIcon,
  Flower2Icon,
  TreesIcon,
  MountainIcon,
  GlobeIcon,
  RocketIcon,
  ShipIcon,
  TrainFrontIcon,
  BikeIcon,
  MapIcon,
  CompassIcon,
  KeyIcon,
  LockIcon,
  MessageCircleIcon,
} from "@lucide/svelte";

export const folderIcons = {
  folder: FolderIcon,
  star: StarIcon,
  heart: HeartIcon,
  sparkles: SparklesIcon,
  flame: FlameIcon,
  sun: SunIcon,
  moon: MoonIcon,
  cloud: CloudIcon,
  zap: ZapIcon,
  crown: CrownIcon,
  gem: GemIcon,
  gift: GiftIcon,
  coffee: CoffeeIcon,
  gamepad: Gamepad2Icon,
  music: MusicIcon,
  camera: CameraIcon,
  image: ImageIcon,
  file: FileIcon,
  user: UserIcon,
  users: UsersIcon,
  paw: PawPrintIcon,
  leaf: LeafIcon,
  sprout: SproutIcon,
  car: CarIcon,
  plane: PlaneIcon,
  house: HouseIcon,
  book: BookOpenIcon,
  bookmark: BookmarkIcon,
  pen: PenIcon,
  scroll: ScrollTextIcon,
  sword: SwordIcon,
  shield: ShieldIcon,
  wand: WandSparklesIcon,
  skull: SkullIcon,
  ghost: GhostIcon,
  cat: CatIcon,
  dog: DogIcon,
  rabbit: RabbitIcon,
  bird: BirdIcon,
  fish: FishIcon,
  bug: BugIcon,
  flower: Flower2Icon,
  trees: TreesIcon,
  mountain: MountainIcon,
  globe: GlobeIcon,
  rocket: RocketIcon,
  ship: ShipIcon,
  train: TrainFrontIcon,
  bike: BikeIcon,
  map: MapIcon,
  compass: CompassIcon,
  key: KeyIcon,
  lock: LockIcon,
  message: MessageCircleIcon,
};

export function getFolderIcon(name?: string) {
  return Object.hasOwn(folderIcons, name ?? "")
    ? folderIcons[name as keyof typeof folderIcons]
    : FolderIcon;
}
